[template]
src = "bird6_ipam.cfg.template"
dest = "/etc/calico/confd/config/bird6_ipam.cfg"
prefix = "/calico"
keys = [
    "/v1/ipam/v6/pool",
    "/staticroutes",
    "/rejectcidrs",
]
reload_cmd = "pkill -HUP bird6 || true"
